config/routes.rb
Tweetvr::Application.routes.draw do
  root to: 'home#show'
  get 'dashboard', to: 'dashboards#show'
  get 'auth/twitter/callback', to: 'sessions#create'

  resources :recordings, only: [:create]
end

app/models/recording.rb
class Recording < ActiveRecord::Base
  validates :start_at, :end_at, overlap: { scope: 'user_id' }
  belongs_to :user
  has_many :tweets
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :recording
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :uid, presence: true, uniqueness: true
  validates :username, presence: true
  validates :token, presence: true
  validates :secret, presence: true

  has_many :recordings

  before_create :generate_remember_token

  def self.find_or_create_from_omniauth(params)
    where(uid: params['uid']).first || create_from_omniauth(params)
  end

  def self.create_from_omniauth(params)
    create! do |user|
      user.uid = params['uid']
      user.username = params['info']['nickname']
      user.image_url = params['info']['image']
      user.token = params['credentials']['token']
      user.secret = params['credentials']['secret']
    end
  end
  private_class_method :create_from_omniauth

  private

  def generate_remember_token
    self.remember_token = SecureRandom.hex
    while User.where(remember_token: self.remember_token).exists?
      self.remember_token = SecureRandom.hex
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authorize
  helper_method :current_user

  def current_user
    User.where(remember_token: session[:remember_token]).first
  end

  private

  def authorize
    unless current_user.present?
      redirect_to root_path
    end
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def show
    @dashboard = Dashboard.new(current_user)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authorize

  def show
  end
end

app/controllers/recordings_controller.rb
class RecordingsController < ApplicationController
  def create
    Recording.create(recording_params)
    redirect_to dashboard_path
  end

  private

  def recording_params
    params.
      require(:recording).
      permit(:start_at, :end_at).
      merge(user: current_user)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authorize

  def create
    user = User.find_or_create_from_omniauth(env['omniauth.auth'])
    session[:remember_token] = user.remember_token
    flash[:notice] = 'Successfully authenticated via Twitter'
    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def username
    "@#{current_user.username}"
  end
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>"><%= value %></div>
  <% end -%>
</div>

app/views/application/_header.html.erb
<% if current_user %>
  <header class="main">
    <nav class="signed-in">
      <%= image_tag current_user.image_url, height: "20", width: "20", class: "avatar" %>
      <span><%= username %></span>
      <%= link_to "Sign Out", "#", class: "sign-out" %>
    </nav>
  </header>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/dashboards/_recording.html.erb
<div>
  <%= l recording.start_at %>
  <%= l recording.end_at %>
</div>

app/views/dashboards/show.html.erb
<section class="dashboard-streams">

  <%= link_to 'New', '#', class: 'new-recording-button js-new-recording-button' %>
  <h1 class="page-title">Your Recordings</h1>

  <section class="user-recording">
    <h2 class="recording-date">June 12, 2014</h2>
    <h1 class="recording-title">Upcoming Recording Title</h1>
    <h3 class="recording-time">
      10:00pm - 11:05pm ET
      <em>(2hrs, 5min)</em>
    </h3>
    <div class="button-container">
      <%= link_to "edit", "#", class: "edit-button" %>
    </div>
  </section>

  <section class="unwatched-recording user-recording">
    <h2 class="recording-date">March 12, 2014</h2>
    <h1 class="recording-title">New Recording Title</h1>
    <h3 class="recording-time">
      10:00pm - 11:05pm ET
      <em>(2hrs, 5min)</em>
    </h3>
    <div class="button-container">
      <%= link_to "play", "#", class: "play-button" %>
    </div>
  </section>

  <section class="user-recording">
    <h2 class="recording-date">March 1, 2014</h2>
    <h1 class="recording-title">Past Recording Title</h1>
    <h3 class="recording-time">
      10:00pm - 11:05pm ET
      <em>(2hrs, 5min)</em>
    </h3>
    <div class="button-container">
      <%= link_to "play", "#", class: "play-button" %>
    </div>
  </section>

  <section class="user-recording">
    <h2 class="recording-date">March 1, 2014</h2>
    <h1 class="recording-title">Past Recording Title</h1>
    <h3 class="recording-time">
      10:00pm - 11:05pm ET
      <em>(2hrs, 5min)</em>
    </h3>
    <div class="button-container">
      <%= link_to "play", "#", class: "play-button" %>
    </div>
  </section>


</section>

<section class="schedule-recording js-schedule-recording">
  <a href="#" aria-label="close window" class="icon-x js-icon-x"></a>
  <%= render partial: 'recording', collection: @dashboard.recordings %>
  <%= render partial: 'recordings/form', recording: @dashboard.new_recording %>
</section>

app/views/home/show.html.erb
<% if current_user %>
  <div>
    <%= link_to 'Visit Dashboard', dashboard_path %>
  </div>
<% else %>
  <div id='user_nav'>
    <%= link_to 'Sign in with Twitter', '/auth/twitter'%>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <title><%= title %></title>
    <%= stylesheet_link_tag :application, :media => 'all' %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//use.typekit.net/uxw4fvx.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>

  <body class="<%= body_class %>">
    <%= render 'application/header'%>
    <%= render 'flashes' -%>
    <section class="main-content">
      <%= yield %>
    </section>
    <%= render 'javascript' %>
  </body>
</html>

app/views/pages/playback.html.erb
<section class="timeline-container">
  <section class="playback-buttons">
    <button aria-label="rewind" class="icon-rewind"></button>
    <button aria-label="play" class="icon-play"></button>
    <!-- <button aria-label="pause" class="icon-pause"></button> -->
    <button aria-label="fast-forward" class="icon-fast-forward"></button>
  </section>
  <section class="progress-bar">
    <time class="time-past">
      01:02:54
    </time>
    <time class="time-remaining">
      00:24:06
    </time>
    <div class="bar-full-length">
      <div class="bar-current">
      </div>
      <div class="bar-scrubber">
      </div>
    </div>
  </section>
</section>

app/views/recordings/_form.html.erb
<%= simple_form_for :recording, url: recordings_path do |f| %>
  <%= f.input :start_at %>
  <%= f.input :end_at %>
  <%= f.button :submit, 'Record' %>
<% end %>